### ISSUE TITLE
Script source

### ISSUE THREAD

**Issue by terjeio** [KiCad/Socket_Strips.pretty#9]
@jkriege2 

I am trying to nail down the version of the make_socket_strips.py script I assume has been used to make these footprints. Any idea?

I ask because I have made a script for generating 3D models and the footprints needs updating, quite a few have 3D offsets and rotation that should be removed. The easy option is to modify the script and rerun it, but I have not found the correct one as all I have checked contains a few "bugs" that I am not prepared to try correct.

**Comment by evanshultz** [comment]
Hi @terjeio! All the scripts for generating footprints should be at https://github.com/pointhi/kicad-footprint-generator. The script you mentioned is at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/pin-headers_socket-strips.

**Comment by terjeio** [comment]
@evanshultz 

Not so, the scripts there contains the same bugs as the master :-(

Example from the generated Socket_Strip_Angled_1x02_Pitch2.00mm.kicad_mod file:

  _(model Socket_Strip.3dshapes/Socket_Strip_Angled_1x02_Pitch2.00mm.wrl..._

No KISYS3DMOD and the model folder name is misspelled _Socket_Strip.3dshapes_, should be plural. 
Line 565 in footprint_scripts_pin_headers.py refers to a variable cc_fabb that does not exsist, but it is used to set another that is never referenced in code so no problem with that, it runs when I comment out that line.

My guess is that the script used to generate the footprints at the kicad repository has never been committed back after being updated.

**Comment by evanshultz** [comment]
I see now. Yes, there must be an updated script that didn't get pulled into that repo. You pinged the right person above.

**Comment by Shackmeister** [comment]
Hi @terjeio if you change cc_fabb to h_fabb at line 581 in footprint_scripts_pin_headers.py the script runs again as it should

**Comment by Shackmeister** [comment]
a PR has been filed https://github.com/pointhi/kicad-footprint-generator/pull/76
